version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting deployment..."
  build:
    commands:
      - aws s3 sync . s3://aiphotoalbumfrontendbucket/ 
  post_build:
    commands:
      - echo "Deployment completed."

artifacts:
  files:
    - NONE
