version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11 
    commands:
      - echo Installing source dependencies...
      # Install dependencies for each Lambda function
      - pip install -r LF1_requirements.txt -t LF1_package/
      - pip install -r LF2_requirements.txt -t LF2_package/

  build:
    commands:
      - echo Build phase...
      # Add the Lambda function code to the packages
      - cp LF1.py LF1_package/
      - cp LF2.py LF2_package/
      # Zip the packages including dependencies
      - cd LF1_package && zip -r ../LF1.zip . && cd ..
      - cd LF2_package && zip -r ../LF2.zip . && cd ..
      - echo "Build completed."

artifacts:
  files:
    - LF1.zip
    - LF2.zip
    - buildspec_deploy.yml

